- clean: ['~', '~/.config']

- shell:
    - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads ~/Pictures
    - cp dojanp.png ~/Pictures/dojanp.png
    - git submodule update --init --recursive # after linking ~/.gitconfig

- link:
    ~/.bashrc: bashrc
    ~/.bashMacrc: bashMacrc
    # ~/.axelrc: axelrc
    ~/.conkyrc: conkyrc
    ~/.conkyMPD: conkyMPD
    ~/.conkyCLOCK: conkyCLOCK
    ~/.config/mpv:
        create: true
        path: config/mpv
    ~/.config/openbox:
        create: true
        path: config/openbox
    ~/.dotfiles: ''
    # ~/.gitconfig: gitconfig
    # ~/.gitignore_global: gitignore_global
    ~/.ncmpcpp/config: ncmpcpp/config
    ~/.rtorrent.rc: rtorrent.rc
    ~/.screenrc: screenrc
    # ~/.tmux.conf: tmux.conf
    # ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.xinitrc: xinitrc
    ~/.Xresources: Xresources    
    ~/.zprezto: prezto/
    ~/.zpreztorc: zpreztorc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
